global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "./rules.yaml"

scrape_configs:
  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: "/metrics"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
